CRITICAL_MINERALS = [
    "aluminium",
    "antimony",
    "arsenic",
    "barite",
    "beryllium",
    "bismuth",
    "cerium",
    "cesium",
    "chromium",
    "cobalt",
    "dysprosium",
    "erbium",
    "europium",
    "fluorspar",
    "gadolinium",
    "gallium",
    "germanium",
    "graphite",
    "hafnium",
    "holmium",
    "indium",
    "iridium",
    "lanthanum",
    "lithium",
    "lutetium",
    "magnesium",
    "manganese",
    "neodymium",
    "nickel",
    "niobium",
    "palladium",
    "platinum",
    "praseodymium",
    "rhodium",
    "rubidium",
    "ruthenium",
    "samarium",
    "scandium",
    "tantalum",
    "tellurium",
    "terbium",
    "thulium",
    "tin",
    "titanium",
    "tungsten",
    "vanadium",
    "ytterbium",
    "yttrium",
    "zinc",
    "zirconium",
]

# These are the mineral names that not within Macrostrat's mineral database
USGS_FORMULAS = {
    "barite": "BaSO4",  # https://www.mindat.org/min-549.html
    "fluorspar": "CaF2",  # https://www.mindat.org/min-1576.html
    "beryllium": "Be",
    "cesium": "Cs",
    "dysprosium": "Dy",
    "erbium": "Er",
    "europium": "Eu",
    "gadolinium": "Gd",
    "gallium": "Ga",
    "germanium": "Ge",
    "hafnium": "Hf",
    "holmium": "Ho",
    "lanthanum": "La",
    "lithium": "Li",
    "lutetium": "Lu",
    "neodymium": "Nd",
    "praseodymium": "Pr",
    "rubidium": "Rb",
    "samarium": "Sm",
    "scandium": "Sc",
    "terbium": "Tb",
    "thulium": "Tm",
    "yttrium": "Y",
    "zirconium": "Zr",
}
