JobBatchName            = "LLM batch inference (testing)"
arguments               = --run_name testing --batch_size 10 --start_index $(idx)

# Environment
universe                = docker
docker_image            = ghcr.io/jasonlo/text2graph_llm:v240208
docker_network_type     = host

# Artefact
Requirements            = (Target.HasCHTCStaging == true)
executable              = chtc_run.sh
transfer_input_files    = chtc_run.sh, main.py
should_transfer_files   = YES
transfer_output_files   = ""

# Logging
stream_output           = true
output                  = condor_log/output.$(Cluster)-$(Process).txt
error                   = condor_log/error.$(Cluster)-$(Process).txt
log                     = condor_log/log.$(Cluster)-$(Process).txt

# Compute resources
request_cpus            = 2
request_memory          = 32GB
request_disk            = 50GB

# Extra GPU settings
request_gpus            = 1
require_gpus            = GlobalMemoryMb >= 30000
Requirements            = (Target.CUDADriverVersion >= 10.1)
+WantGPULab             = true
+GPUJobLength           = "short"

queue idx in 0