version: '3.8'

services:

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - $OLLAMA_MODEL_DIR:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ $GPU_IDX ]
  api:
    build:
      dockerfile: ./api/Dockerfile
    ports:
      - 4502:4502
    env_file: .env
