version: '3.8'

services:

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - $OLLAMA_MODEL_DIR:/root/.ollama
    # If you don't have any NVidia GPU on your machine, please remove `deploy` block
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  api:
    build:
      dockerfile: ./api/Dockerfile
    ports:
      - $API_PORT:4502
    env_file: .env

  demo:
    build:
      dockerfile: ./demo/Dockerfile
    ports:
      - $DEMO_PORT:8501
    env_file: .env
