version: '3.8'

services:
  ollama0:
    container_name: ollama0
    image: ollama/ollama:latest
    ports:
      - "12000:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ '0' ]
  ollama1:
    container_name: ollama1
    image: ollama/ollama:latest
    ports:
      - "12001:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ '1' ]
  ollama2:
    container_name: ollama2
    image: ollama/ollama:latest
    ports:
      - "12002:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ '2' ]
  ollama3:
    container_name: ollama3
    image: ollama/ollama:latest
    ports:
      - "12003:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ '3' ]
  ollama4:
    container_name: ollama4
    image: ollama/ollama:latest
    ports:
      - "12004:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ '4' ]
  ollama5:
    container_name: ollama5
    image: ollama/ollama:latest
    ports:
      - "12005:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ '5' ]
  # ollama6: # Broken GPU
  #   container_name: ollama6
  #   image: ollama/ollama:latest
  #   ports:
  #     - "12006:11434"
  #   volumes:
  #     - ollama:/root/.ollama
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [ gpu ]
  #             device_ids: [ '6' ]
  ollama7:
    container_name: ollama7
    image: ollama/ollama:latest
    ports:
      - "12007:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ '7' ]

volumes:
  ollama:
